server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library;encrypt=true;trustServerCertificate=true
    username: zuhre
    password: zuhre060
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

  thymeleaf:
    cache: false
